itec:
  build: .
  ports:
   - "8080:8080"
  links:
   - mongodb:mongo
   - metrics:metrics
  entrypoint:
   - java
   - -Dspring.data.mongodb.uri=mongodb://mongo:27017/itec
   - -Dgraphite.enabled=true
   - -Dgraphite.hostname=metrics
   - -jar
   - /app.jar

mongodb:
  image: mongo
  expose:
   - "27017"

metrics:
  image: kamon/grafana_graphite
  ports:
    - '80:80'
    - '81:81'
    - '8125:8125/udp'
    - '8126:8126'
    - '2003:2003'
  volumes:
    - ./data/whisper:/opt/graphite/storage/whisper
    - ./data/grafana:/opt/grafana/data
    - ./log/graphite:/opt/graphite/storage/log